/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author SergioMarquez
 */
public class ViewProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewProductos
     */
    public ViewProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_codigo = new javax.swing.JLabel();
        jl_producto = new javax.swing.JLabel();
        jl_cantidad = new javax.swing.JLabel();
        jl_precio_venta = new javax.swing.JLabel();
        jl_precio_compra = new javax.swing.JLabel();
        jtf_producto = new javax.swing.JTextField();
        jtf_cantidad = new javax.swing.JTextField();
        jtf_precio_compra = new javax.swing.JTextField();
        jtf_codigo = new javax.swing.JTextField();
        jtf_precio_venta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_productos = new javax.swing.JTable();
        jl_buscar = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jbtn_mostrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Productos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Registro de productos"));
        jPanel1.setLayout(null);

        jl_codigo.setText("Codigo");
        jPanel1.add(jl_codigo);
        jl_codigo.setBounds(20, 30, 90, 20);

        jl_producto.setText("Producto");
        jPanel1.add(jl_producto);
        jl_producto.setBounds(20, 80, 80, 20);

        jl_cantidad.setText("Cantidad");
        jPanel1.add(jl_cantidad);
        jl_cantidad.setBounds(20, 110, 80, 20);

        jl_precio_venta.setText("Precio de venta");
        jPanel1.add(jl_precio_venta);
        jl_precio_venta.setBounds(20, 170, 120, 20);

        jl_precio_compra.setText("Precio de compra");
        jPanel1.add(jl_precio_compra);
        jl_precio_compra.setBounds(20, 140, 140, 20);
        jPanel1.add(jtf_producto);
        jtf_producto.setBounds(90, 80, 170, 20);
        jPanel1.add(jtf_cantidad);
        jtf_cantidad.setBounds(90, 110, 110, 20);
        jPanel1.add(jtf_precio_compra);
        jtf_precio_compra.setBounds(150, 140, 110, 20);

        jtf_codigo.setForeground(new java.awt.Color(0, 0, 222));
        jPanel1.add(jtf_codigo);
        jtf_codigo.setBounds(70, 30, 100, 20);
        jPanel1.add(jtf_precio_venta);
        jtf_precio_venta.setBounds(150, 170, 110, 20);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jbtn_nuevo.setText("Nuevo");
        jPanel2.add(jbtn_nuevo);
        jbtn_nuevo.setBounds(30, 20, 100, 24);

        jbtn_guardar.setText("Guardar");
        jPanel2.add(jbtn_guardar);
        jbtn_guardar.setBounds(140, 20, 100, 24);

        jbtn_modificar.setText("Modificar");
        jPanel2.add(jbtn_modificar);
        jbtn_modificar.setBounds(30, 60, 100, 24);

        jbtn_eliminar.setText("Eliminar");
        jPanel2.add(jbtn_eliminar);
        jbtn_eliminar.setBounds(140, 60, 100, 24);

        jbtn_cancelar.setText("Cancelar");
        jPanel2.add(jbtn_cancelar);
        jbtn_cancelar.setBounds(80, 100, 110, 24);

        jbtn_primero.setText("|<");
        jPanel2.add(jbtn_primero);
        jbtn_primero.setBounds(10, 140, 50, 24);

        jbtn_ultimo.setText(">|");
        jPanel2.add(jbtn_ultimo);
        jbtn_ultimo.setBounds(210, 140, 52, 24);

        jbtn_anterior.setText("<<");
        jPanel2.add(jbtn_anterior);
        jbtn_anterior.setBounds(70, 140, 60, 24);

        jbtn_siguiente.setText(">>");
        jPanel2.add(jbtn_siguiente);
        jbtn_siguiente.setBounds(140, 140, 60, 24);

        jtable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtable_productos);

        jl_buscar.setText("Buscar");

        jbtn_mostrar.setText("Mostrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jl_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jbtn_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_mostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_cancelar;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_guardar;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_mostrar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    private javax.swing.JLabel jl_buscar;
    private javax.swing.JLabel jl_cantidad;
    private javax.swing.JLabel jl_codigo;
    private javax.swing.JLabel jl_precio_compra;
    private javax.swing.JLabel jl_precio_venta;
    private javax.swing.JLabel jl_producto;
    public javax.swing.JTable jtable_productos;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_cantidad;
    public javax.swing.JTextField jtf_codigo;
    public javax.swing.JTextField jtf_precio_compra;
    public javax.swing.JTextField jtf_precio_venta;
    public javax.swing.JTextField jtf_producto;
    // End of variables declaration//GEN-END:variables
}
