/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author SergioMarquez
 */
public class ViewIngredientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewIngredientes
     */
    public ViewIngredientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_codigo = new javax.swing.JLabel();
        jl_ingrediente = new javax.swing.JLabel();
        jtf_codigo = new javax.swing.JTextField();
        jtf_ingrediente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_modificar = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_ingrediente = new javax.swing.JTable();
        jl_buscar = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jbtn_mostrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ingredientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Registro de Ingredientes"));
        jPanel1.setLayout(null);

        jl_codigo.setText("Codigo");
        jPanel1.add(jl_codigo);
        jl_codigo.setBounds(20, 30, 90, 20);

        jl_ingrediente.setText("Ingrediente");
        jPanel1.add(jl_ingrediente);
        jl_ingrediente.setBounds(20, 80, 100, 20);

        jtf_codigo.setForeground(new java.awt.Color(0, 0, 222));
        jPanel1.add(jtf_codigo);
        jtf_codigo.setBounds(90, 30, 100, 20);
        jPanel1.add(jtf_ingrediente);
        jtf_ingrediente.setBounds(110, 80, 130, 20);

        jPanel2.setLayout(null);

        jbtn_nuevo.setText("Nuevo");
        jPanel2.add(jbtn_nuevo);
        jbtn_nuevo.setBounds(20, 30, 100, 24);

        jbtn_modificar.setText("Modificar");
        jPanel2.add(jbtn_modificar);
        jbtn_modificar.setBounds(20, 70, 100, 24);

        jbtn_guardar.setText("Guardar");
        jPanel2.add(jbtn_guardar);
        jbtn_guardar.setBounds(130, 30, 100, 24);

        jbtn_eliminar.setText("Eliminar");
        jPanel2.add(jbtn_eliminar);
        jbtn_eliminar.setBounds(130, 70, 100, 24);

        jbtn_cancelar.setText("Cancelar");
        jPanel2.add(jbtn_cancelar);
        jbtn_cancelar.setBounds(80, 110, 100, 24);

        jbtn_ultimo.setText(">|");
        jPanel2.add(jbtn_ultimo);
        jbtn_ultimo.setBounds(210, 160, 50, 24);

        jbtn_primero.setText("|<");
        jPanel2.add(jbtn_primero);
        jbtn_primero.setBounds(10, 160, 50, 24);

        jbtn_anterior.setText("<<");
        jPanel2.add(jbtn_anterior);
        jbtn_anterior.setBounds(70, 160, 60, 24);

        jbtn_siguiente.setText(">>");
        jPanel2.add(jbtn_siguiente);
        jbtn_siguiente.setBounds(140, 160, 60, 24);

        jtable_ingrediente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtable_ingrediente);

        jl_buscar.setText("Buscar");

        jbtn_mostrar.setText("Mostrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jl_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jbtn_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_mostrar))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_cancelar;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_guardar;
    public javax.swing.JButton jbtn_modificar;
    public javax.swing.JButton jbtn_mostrar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    private javax.swing.JLabel jl_buscar;
    private javax.swing.JLabel jl_codigo;
    private javax.swing.JLabel jl_ingrediente;
    public javax.swing.JTable jtable_ingrediente;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_codigo;
    public javax.swing.JTextField jtf_ingrediente;
    // End of variables declaration//GEN-END:variables
}
