/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author SergioMarquez
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdesktop_principal = new javax.swing.JDesktopPane();
        jmbarr_archivo = new javax.swing.JMenuBar();
        jmenu_archivo = new javax.swing.JMenu();
        jm_item_sesion = new javax.swing.JMenuItem();
        jm_item_salir = new javax.swing.JMenuItem();
        jmenu_registros = new javax.swing.JMenu();
        jm_item_clientes_re = new javax.swing.JMenuItem();
        jm_item_productos_re = new javax.swing.JMenuItem();
        jm_item_ingredientes = new javax.swing.JMenuItem();
        jmenu_pedidos = new javax.swing.JMenu();
        jm_item_abrir = new javax.swing.JMenuItem();
        jmenu_consultas = new javax.swing.JMenu();
        jm_item_clientes_co = new javax.swing.JMenuItem();
        jm_item_productos_co = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdesktop_principal.setBackground(new java.awt.Color(25, 153, 153));

        javax.swing.GroupLayout jdesktop_principalLayout = new javax.swing.GroupLayout(jdesktop_principal);
        jdesktop_principal.setLayout(jdesktop_principalLayout);
        jdesktop_principalLayout.setHorizontalGroup(
            jdesktop_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        jdesktop_principalLayout.setVerticalGroup(
            jdesktop_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jmenu_archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo-icono-5812-32.png"))); // NOI18N
        jmenu_archivo.setText("Archivo");

        jm_item_sesion.setText("Cerrar Sesion");
        jmenu_archivo.add(jm_item_sesion);

        jm_item_salir.setText("Salir");
        jmenu_archivo.add(jm_item_salir);

        jmbarr_archivo.add(jmenu_archivo);

        jmenu_registros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/signatura-icono-8756-32.png"))); // NOI18N
        jmenu_registros.setText("Registros");

        jm_item_clientes_re.setText("Clientes");
        jmenu_registros.add(jm_item_clientes_re);

        jm_item_productos_re.setText("Productos");
        jmenu_registros.add(jm_item_productos_re);

        jm_item_ingredientes.setText("Ingredientes");
        jmenu_registros.add(jm_item_ingredientes);

        jmbarr_archivo.add(jmenu_registros);

        jmenu_pedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seleccione-ver-icono-6736-32.png"))); // NOI18N
        jmenu_pedidos.setText("Pedidos");

        jm_item_abrir.setText("Abrir");
        jmenu_pedidos.add(jm_item_abrir);

        jmbarr_archivo.add(jmenu_pedidos);

        jmenu_consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar-archivo-icono-5865-32.png"))); // NOI18N
        jmenu_consultas.setText("Consultas");

        jm_item_clientes_co.setText("Clientes");
        jmenu_consultas.add(jm_item_clientes_co);

        jm_item_productos_co.setText("Productos");
        jmenu_consultas.add(jm_item_productos_co);

        jmbarr_archivo.add(jmenu_consultas);

        setJMenuBar(jmbarr_archivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdesktop_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdesktop_principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jdesktop_principal;
    public javax.swing.JMenuItem jm_item_abrir;
    public javax.swing.JMenuItem jm_item_clientes_co;
    public javax.swing.JMenuItem jm_item_clientes_re;
    public javax.swing.JMenuItem jm_item_ingredientes;
    public javax.swing.JMenuItem jm_item_productos_co;
    public javax.swing.JMenuItem jm_item_productos_re;
    public javax.swing.JMenuItem jm_item_salir;
    public javax.swing.JMenuItem jm_item_sesion;
    private javax.swing.JMenuBar jmbarr_archivo;
    private javax.swing.JMenu jmenu_archivo;
    private javax.swing.JMenu jmenu_consultas;
    private javax.swing.JMenu jmenu_pedidos;
    private javax.swing.JMenu jmenu_registros;
    // End of variables declaration//GEN-END:variables
}
